### ISSUE TITLE
Error raised when date is blank

### ISSUE THREAD

**Issue by nnc** [minimul/iif-parser#2]
There is a problem when some lines in .iif file don't have a date, like in this example.

```
!TRNS   TRNSTYPE    DATE    ACCNT   NAME    AMOUNT  DOCNUM
!SPL    TRNSTYPE    DATE    ACCNT   NAME    AMOUNT  DOCNUM
!ENDTRNS
TRNS    EFT     05/14/2015  Checking    United States Treasury  -57.64   
SPL EFT     05/14/2015  Tax Transfer        23.36    
SPL EFT         Tax Transfer        23.36    
SPL EFT         Tax Transfer        5.46     
SPL EFT         Tax Transfer        5.46     
ENDTRNS
```

Error is raised when processing line 6, first one without the date.

```
[7] pry(main)> iif = Iif::Parser.new(fc)
NoMethodError: undefined method `div' for nil:NilClass
from /Users/nnc/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/iif-parser-1.0.1/lib/iif/parser.rb:78:in `new’
```

I monkey patched it to return `nil` for lines with blank date, as that works well in my particular case. But I'm not familiar with this file format, so I'm not sure how this can best be handled in a more general way.

Thanks for this gem, btw. I found it useful :)

**Comment by minimul** [comment]
Returning nil would be fine. Can you submit a PR? Or if you attach the exact .iif file I will put in the fix..
Thanks.
